### ISSUE TITLE
failing to build

### ISSUE THREAD

**Issue by Vikas-Jilla** [kiwi-bop/flutter_crashlytics#73]
** BUILD FAILED **
```
Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    /Users/home/Documents/flutter/test_crashlytics/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'flutter_crashlytics/FlutterCrashlyticsPlugin.h' file not found
    #import <flutter_crashlytics/FlutterCrashlyticsPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.1 18B75, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

**Pod File**
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'Firebase/Core'
  # Pods for Runner

end
```

**Dependencies in pubspec.yaml file**
```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_crashlytics: ^0.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
```
